[package]
name = "proofdown_validate"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
proofdown_ast = { path = "../proofdown_ast" }

[dev-dependencies]
proofdown_parser = { path = "../proofdown_parser" }
