name: GitHub Pages

on:
  push:
    branches: [ main ]

concurrency:
  group: Pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pages:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install mdBook
        run: cargo install mdbook --version ^0.4
      - name: Build book
        run: mdbook build book
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/book
